# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
arr2q = np.zeros(10)
arr2q

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [3]:
arr3q = np.arange (10,50)
arr3q

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [4]:
arr3q.shape

(40,)

5. Print the type of the previous array in question 3

In [5]:
arr3q.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [6]:
print(np.__version__)
print(np.show_config())

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/Anaconda/ShahidAI\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'E:/Anaconda/ShahidAI\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/Anaconda/ShahidAI\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'E:/A

7. Print the dimension of the array in question 3


In [7]:
arr3q.ndim

1

8. Create a boolean array with all the True values

In [8]:
arr8q = np.array ([-1,2,0, None,"Str", -0.5,-33.5,45,5], dtype=bool)
arr8q

array([ True,  True, False, False,  True,  True,  True,  True,  True])

9. Create a two dimensional array




In [9]:
arr9q = np.arange(12).reshape(3,4)
arr9q

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

10. Create a three dimensional array



In [10]:
arr10q=np.arange(27).reshape(3,3,3)
arr10q

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
arr11q = np.arange(10)
arr11q = arr11q[::-1]
arr11q

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

12. Create a null vector of size 10 but the fifth value which is 1 

In [12]:
arr12q = np.zeros(10)
arr12q[4] = 1
arr12q

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [13]:
arr13q = np.identity(3)
arr13q

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [14]:
arr = np.array([1, 2, 3, 4, 5])
arr14q = arr.astype(np.float)
print (arr14q)
print (arr14q.dtype)

[1. 2. 3. 4. 5.]
float64


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [15]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
print (arr1*arr2)

[[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [16]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr3 = arr1 == arr2
print ("One by One Comparison of arr1 & arr2")
print (arr3)
print ()
print ("Full Comparison of arr1 & arr2")
print (arr3.all())

One by One Comparison of arr1 & arr2
[[False False False]
 [False False False]]

Full Comparison of arr1 & arr2
False


17. Extract all odd numbers from arr with values(0-9)

In [17]:
arr17q = np.arange(10)
print ("Our Array", arr17q)
print ("Odd numbers only")
print (arr17q[arr17q%2 == 1])

Our Array [0 1 2 3 4 5 6 7 8 9]
Odd numbers only
[1 3 5 7 9]


18. Replace all odd numbers to -1 from previous array

In [18]:
# Using the previous example
arr18q = np.arange(10)
print ("Our Array", arr17q)
print ("Replacing only odd numbers with -1")
arr18q[arr17q%2 == 1]= -1
print (arr18q)


Our Array [0 1 2 3 4 5 6 7 8 9]
Replacing only odd numbers with -1
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [19]:
arr = np.arange(10)
arr[5:9]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [20]:
arr20q = np.ones(10, dtype=int)
arr20q[1:9]=0
arr20q

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [21]:
arr2d = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
arr2d[arr2d==5] =12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [22]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [23]:
arr23q = np.arange(10).reshape(2,5)
print ("Our Array - arr23q")
print (arr23q)
print ("Slicing 1st dimension of 1D array")
print (arr23q[0])

Our Array - arr23q
[[0 1 2 3 4]
 [5 6 7 8 9]]
Slicing 1st dimension of 1D array
[0 1 2 3 4]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [24]:
arr24q = np.arange(10).reshape(2,5)
print ("Our Array - arr24q")
print (arr24q)
print ("Slicing 2nd dimension of 1D array")
print (arr24q[1])

Our Array - arr24q
[[0 1 2 3 4]
 [5 6 7 8 9]]
Slicing 2nd dimension of 1D array
[5 6 7 8 9]


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [25]:
arr25q = np.arange(10).reshape(2,5)
print ("Our Array - arr24q")
print (arr25q)
print ("Slicing 2nd dimension of 1D array")
print (arr25q[:,2:3])

Our Array - arr24q
[[0 1 2 3 4]
 [5 6 7 8 9]]
Slicing 2nd dimension of 1D array
[[2]
 [7]]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [26]:
arr26q = np.random.randint(100, size=(10,10))
print ("Our Array")
print (arr26q)
print ("\nMinimum in Array = ", np.min(arr26q))
print ("\nMaximum in Array = ", np.max(arr26q))

Our Array
[[40 27 85 54  2 39 95 98 41 26]
 [23 54 97 68 42 49 68 43  4 32]
 [37 61 37 22 72 94 13 31 98 70]
 [25 30 81 27 36 51 39 73 67 92]
 [99 36  0 52 33  4 62 26 94 95]
 [63 19 42 40 23 95 81 39  4  0]
 [ 9 79 10  6  8 11  8  6 37 58]
 [97 66 89 10 95 80 64 70 78 62]
 [89 47 51 42 53 81 85 91 51 35]
 [74  7 52 18 51 60  5 67 17  7]]

Minimum in Array =  0

Maximum in Array =  99


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print ("Common Elements", np.intersect1d(a,b))

Common Elements [2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [28]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
ab, a_indices, b_indices = np.intersect1d(a,b, return_indices = True)
print ("Position of Common Elements")
print ("Array a = ", a_indices)
print ("Array b = ", b_indices)

Position of Common Elements
Array a =  [1 5]
Array b =  [1 5]


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [29]:
data = np.random.randn(7, 4)
print ("Our array\n", data)
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print ("Data Values not equal to Will\n",data[names!="Will"])

Our array
 [[-3.34378617e-01 -1.28795143e+00  1.07121086e+00  8.86665346e-01]
 [-1.24812553e-01  4.98377503e-01  2.06998821e+00  4.05835530e-01]
 [ 1.07879818e+00  1.35617829e-01 -2.14131797e-01 -3.03401624e-02]
 [ 6.30482364e-01  5.01376602e-01 -4.55331878e-01 -1.01087242e+00]
 [-5.89718005e-01 -1.50825395e+00  6.13287022e-01 -9.71223964e-01]
 [-1.88311784e+00 -5.22847759e-01 -1.17826129e+00 -7.37516071e-01]
 [ 2.60099762e-01  2.05576393e-03  7.57299487e-01 -6.80235001e-01]]
Data Values not equal to Will
 [[-3.34378617e-01 -1.28795143e+00  1.07121086e+00  8.86665346e-01]
 [-1.24812553e-01  4.98377503e-01  2.06998821e+00  4.05835530e-01]
 [ 6.30482364e-01  5.01376602e-01 -4.55331878e-01 -1.01087242e+00]
 [-1.88311784e+00 -5.22847759e-01 -1.17826129e+00 -7.37516071e-01]
 [ 2.60099762e-01  2.05576393e-03  7.57299487e-01 -6.80235001e-01]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [30]:
mask = (names!="Will") & (names!="Joe")
data[mask]

array([[-0.33437862, -1.28795143,  1.07121086,  0.88666535],
       [ 0.63048236,  0.5013766 , -0.45533188, -1.01087242]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [31]:
arr31q = np.random.uniform(1,15, size=(5,3))
arr31q

array([[ 1.47736572,  7.40577697,  4.84810231],
       [11.8762048 ,  6.50185663, 10.39025785],
       [14.28312312, 11.45859547, 13.24153814],
       [ 1.88860657,  6.83784527, 12.60388423],
       [13.97013819,  3.08503899, 14.8677139 ]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [32]:
arr31q = np.random.uniform(1,15, size=(2,2,4))
arr31q

array([[[ 9.06112432,  1.74962875,  1.90881065,  9.47923468],
        [13.03701492,  3.81145184,  2.65907695,  9.25466816]],

       [[ 3.51779788, 10.96122881, 14.77016853, 12.01283011],
        [12.81023656,  6.82901294,  1.5837829 ,  7.62936346]]])

33. Swap axes of the array you created in Question 32

In [33]:
arr31q.transpose()

array([[[ 9.06112432,  3.51779788],
        [13.03701492, 12.81023656]],

       [[ 1.74962875, 10.96122881],
        [ 3.81145184,  6.82901294]],

       [[ 1.90881065, 14.77016853],
        [ 2.65907695,  1.5837829 ]],

       [[ 9.47923468, 12.01283011],
        [ 9.25466816,  7.62936346]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [34]:
arr34q = np.arange(10)
arr34q_sqrt = np.sqrt(arr34q)
arr34q_sqrt[arr34q_sqrt < 0.5] = 0
arr34q_sqrt

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [35]:
a = np.random.randint(12, size=(3,3))
b = np.random.randint(12,size=(3,3))
print ("Array 1 = a\n", a)
print ("Array 1 = b\n", b)
arr35q = np.maximum(a, b)
print ("Maximum Value Array\n", arr35q)

Array 1 = a
 [[ 3  2  2]
 [ 5  6  2]
 [ 9 11  3]]
Array 1 = b
 [[9 6 2]
 [0 7 1]
 [4 3 1]]
Maximum Value Array
 [[ 9  6  2]
 [ 5  7  2]
 [ 9 11  3]]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [36]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [37]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
for x in b:
    for y in range (len(a)):
        if a[y] == x:
            print ("Similar Item in b & a is", a[y])
            a = np.delete(a,y)
print (a)           
print ("===================================")
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
print ("Another Method - np.setdiff1d(a,b)")
print ("New Array", np.setdiff1d(a,b))

Similar Item in b & a is 5
[1 2 3 4]
Another Method - np.setdiff1d(a,b)
New Array [1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [38]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
print ("Our Array\n",sampleArray)
deleted_array = np.delete(sampleArray,1,axis=1)
inserted_array = np.insert(deleted_array, 1, newColumn, axis=1)
print ("Our new array with inserted column\n", inserted_array)

Our Array
 [[34 43 73]
 [82 22 12]
 [53 94 66]]
Our new array with inserted column
 [[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [39]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [40]:
arr40q = np.random.randint(20, size=(4,5))
print ("Our Array\n",arr40q)
cumsum_arr40q = np.cumsum(arr40q, axis=1)
print ("Our cumsum array")
print (cumsum_arr40q)

Our Array
 [[ 5  5  6 17 18]
 [17 16  8 15  3]
 [14  3 13 13 18]
 [17  2 16  8  4]]
Our cumsum array
[[ 5 10 16 33 51]
 [17 33 41 56 59]
 [14 17 30 43 61]
 [17 19 35 43 47]]
